### ISSUE TITLE
ModuleNotFoundError: No module named 'partio'

### ISSUE THREAD

**Issue by bakhtiyar-k** [wdas/partio#101]
Hello, @davvid 

I created a conda virtual environment (python 3.7.11) and ran the lines given in the Super impatient building guide. 

How do I bind partio with python so i can import it?

**Comment by davvid** [comment]
Our build conventions are virtualenv-compatible. I'm not sure if it's conventional to install directly into your conda venv, but if it's just a directory on disk, and it's already activated, then doing

```make install prefix=/path/to/the/venv` and it should create the usual `lib/python3.7/site-packages/` structure inside of it.

Otherwise if you aren't installing it into that global location then you can set the PYTHONPATH environment variable to the `$HOME/local/lib/python3.7/site-packages` directory and then python should be able to import the modules.
