### ISSUE TITLE
ModuleNotFoundError: No module named 'partio'

### ISSUE THREAD

**Issue by DimitriosApostolosPatsiouTerzidis** [wdas/partio#106]
I know that this may be a trivial issue, but still I've found myself in a deadend trying to functionally install partio and make it able to be used by python. Say I've built partio following the readme instructions but this is not enough for my scripts to been able to use partio. I don't know if there are still people answering here, but I need this fixed for my thesis. I've also tried to install using the "Setup.py" with the command pip install . --use-pep-517 but for some reason i can't understand the setup is disrupted  by an error for not finding CMake which is already installed in the expected directories. If you need further information feel free to ask. 
Thank you for your time and possible response.

**Comment by DimitriosApostolosPatsiouTerzidis** [comment]
As I assumed my problem was completely personal and not exactly technical. For some reason SWIG was malfunctioning and I had to reinstall it from scratch.

**Comment by davvid** [comment]
In case it helps anyone else, if you're using a virtualenv then installing partio into the virtualenv is a surefire way to get things working.

For example, after activating the virtualenv, run `make install prefix=<path/to/the/virtualenv>` and that should do the right thing and  install partio's modules into the standard `<virtualenv>/lib/pythonX.Y/site-packages` directory structure inside of the virtualenv directory.

If you install into a different installation prefix then you usually have to set the `PYTHONPATH` environment variable to point into the `<prefix>/lib/pythonX.Y/site-packages` directory in order for Python to find the modules. Alternatively, append the path to the installed `.../site-packages` directory to `sys.path` in your script and  that'll get python to look there when importing modules.

Further reading: https://docs.python.org/3/library/sys_path_init.html
