### ISSUE TITLE
scons error

### ISSUE THREAD

**Issue by lynxcode** [wdas/partio#49]
... scons: building associated VariantDir targets: build/Linux-3.19.0-x86_64-optimize
scanForFurtherDocFiles(["build/Linux-3.19.0-x86_64-optimize/src/doc/dummyTarget"], ["src/doc/doc/html/index.html"])
Install file: "build/Linux-3.19.0-x86_64-optimize/src/tools/partinfo" as "dist/Linux-3.19.0-x86_64-optimize/bin/partinfo"
Install file: "build/Linux-3.19.0-x86_64-optimize/src/tools/partview" as "dist/Linux-3.19.0-x86_64-optimize/bin/partview"
scons: **\* [build/Linux-3.19.0-x86_64-optimize/src/py/libpartio.so] Source file: src/py/partio.i is static and is not compatible with shared target: build/Linux-3.19.0-x86_64-optimize/src/py/libpartio.so
scons: building terminated because of errors.

how can I fix error?

**Comment by davvid** [comment]
We've switched to cmake so hopefully this is a non-issue now.
