### ISSUE TITLE
Is 0.1.1 really the version as noted in CMakeLists.txt?

### ISSUE THREAD

**Issue by dracwyrm** [wdas/partio#72]
Hi,

As the title states, v0.1.1 is still listed here: https://github.com/wdas/partio/blob/master/CMakeLists.txt#L38

Is this correct? Is this safe to change when packaging it?

Thanks.

**Comment by davvid** [comment]
From a maintenance POV, I was thinking we could implement something similar to wdas/ptex#35 and autogenerate that field from Git.

To aid builds and packaging where we might have shallow clones, or not all of the tags available, that PR allows dropping in a file at the root called `version` with a version number in it that'll be slurped in by the cmake build.  So it's either you have a git repo with history where the build can query for the version, or you can override it with a simple text file at the root of the repo.

Would that work for packaging partio too?  If so we can add that before the next release.  My commit was a quick hack that simply tweaks the hard-coded version to `1.5.0`. Longer-term I'd prefer to not hard-code it and convey the version through git tags instead.

**Comment by dracwyrm** [comment]
Thanks. This clears things up a lot! I was wondering how I should treat that, like a library version or something. :) Automation is always a good thing.

Thanks again,
Jon
