### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by fernape** [wdas/partio#77]
The 1.10.0 release claims to support Python 3 but scripts like partinspect and partedit still use print without parenthesis so they are not executable with Python 3.

**Comment by davvid** [comment]
Thanks for the heads-up.  Yeah, I was mainly porting the test suite first.  I'll fix those up shortly.

**Comment by danfe** [comment]
Another thing: in Python 3, `k = d.keys(); k.sort()` [no longer works](https://docs.python.org/3/whatsnew/3.0.html), yet it's still used in `src/tools/partedit.py`.  Consider something like this:
```patch
@@ -72,9 +72,7 @@
     numAttr = numAttributesFunc()
 
     nameToIndex = {attributeInfoFunc(anum).name:anum for anum in range(numAttr)}
-    names = nameToIndex.keys()
-    if sort:
-        names.sort()
+    names = sorted(nameToIndex) if sort else nameToIndex.keys()
```
