### ISSUE TITLE
Homebrew has a very very old Partio

### ISSUE THREAD

**Issue by lgritz** [wdas/partio#79]
On MacOS, for users who use homebrew ("brew install partio"), they are getting Partio 1.1.0, which -- oh dear -- dates from 2012.

I know that you guys don't maintain the homebrew recipe for building partio, but clearly whoever once did is not updating it regularly, so maybe it's in the interest of the Partio project for its maintainers to occasionally submit a PR to homebrew to bump the version to something modern?

**Comment by davvid** [comment]
Thanks for the heads-up, Larry.  We've filed an internal issue to follow-up and update homebrew.

**Comment by davvid** [comment]
This has been resolved. A kind stranger has already packaged more recent versions.

A formula to update to the very latest version has been submitted to homebrew-core.

https://github.com/Homebrew/homebrew-core/pull/135583

**Comment by lgritz** [comment]
I feel like this Issue's timeline is a preview of what open source development will be like with the Alpha Centauri dev team.
