### ISSUE TITLE
Please provide a versioned library

### ISSUE THREAD

**Issue by luyatshimbalanga** [wdas/partio#82]
Hello,
I am a Fedora contributor aiming to package partio. The [review process](https://bugzilla.redhat.com/show_bug.cgi?id=1858531#c1) suggested to include the versionned library on `src/lib/CMakeLists.txt` using the following line:
```
set_target_properties(partio PROPERTIES
    OUTPUT_NAME partio POSITION_INDEPENDENT_CODE ON
    VERSION ${CMAKE_PROJECT_VERSION}
    SOVERSION 1 
)
```
Edit: correct line.
Hopefully, you will provide the suggestion on the next release. 
Thanks in advance.

**Comment by davvid** [comment]
Thanks for the sug @luyatshimbalanga -- yes, this would be good to do.

**Comment by danfe** [comment]
For `${CMAKE_PROJECT_VERSION}` expansion to work, `project()` should be called with `VERSION` argument in the top-level `CMakeLists.txt`.
