### ISSUE TITLE
Houdini Geo export what is papi?

### ISSUE THREAD

**Issue by jmacey** [wdas/partio#87]
Hi, 

I do an exercise with my students where I get them to write out particles as Houdini Geo in a C++ program and we write our own exporter but I suggest they also look (and later use) partio as a comparison. Whilst doing this I know what all the elements are in the file / exporter apart from writing the string 

```generator 1 index 1 papi``` 

What does papi do? I have tried removing it and it doesn't load into Houdini (we use the academic version). and I can't find it mentioned in any of the geo documentation on the SideFX site. So  I  would be nice to know what it actually means so I can tell the students (rather than saying we need to write it I don't know why!).

Thanks for your help and the library we find it nice and easy to use for student projects.

Jon

**Comment by davvid** [comment]
@aselle will probably know for sure, but my guess is that "papi" stands for "Particle API", which may have been a psuedonym for partio early on.

According to https://www.sidefx.com/docs/houdini/io/formats/geo.html#attribute-definitions this is defining a primitive attribute (over all the points, which make up this logical "prim"):

        generator 1 index 1 papi

That's saying that it's has the name "generator" (referring to the program or library that generated the file) of length 1.  It's effectively a metadata comment.

The single entry is `index 1 papi` which defines an indexed string ("index") attribute with 1 string value: `papi`, which is effectively just some metadata that indicates that the file was generated by "papi" aka "partio".

It should work just fine if you enter any other string there, eg. "partio".  The example from the houdini docs has:

        mat 1 index 3 marble gold crystal_glass3

Which is a scalar (1) attribute called "mat" with a single entry, also an indexed string attribute, with 3 values: "marble", "gold", and "crystall_glass3"

**Comment by davvid** [comment]
In the Geometry spreadsheet in Houdini the string will show up under the "Primitive" section (click on the top-left mode switcher tool buttons).
