### ISSUE TITLE
PyQt5 support for partinspect and partedit

### ISSUE THREAD

**Issue by danfe** [wdas/partio#89]
There are two Python scripts, _partinspect_ and _partedit_, which are not PyQt5-ready when used verbatim.  Simply changing `from Qt` to `from PyQt5` in the import section allows me to run _partinspect_.  For _partedit_ however it's not enough, it then complains about `from minibar.gui import mbWidgetStyling` and I'm not sure what to do about this.

**Comment by davvid** [comment]
`Qt.py` is https://github.com/mottosso/Qt.py which can avoid having to touch those parts (it allows for portability between PyQt4/5 and PySide2).

Sorry about the minibar imports -- for that what we'd probably want to do is have it catch `ImportError` and disable that functionality when those modules aren't available.
