### ISSUE TITLE
partio 1.14.0 osx build failure

### ISSUE THREAD

**Issue by chenrui333** [wdas/partio#91]
👋 trying to build the latest release, but run into some build issue. 

The error log is as below:

<details>
<summary>build failure</summary>

```
CMake Error at src/tools/CMakeLists.txt:38 (add_executable):
  Target "partview" links to target "OpenGL::OpenGL" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_C_FLAGS_RELEASE
```

</details>

Full build log is here, https://github.com/Homebrew/homebrew-core/runs/1547382827
relates to https://github.com/Homebrew/homebrew-core/pull/66889

And help would be appreciated!

**Comment by chenrui333** [comment]
cc @davvid

**Comment by davvid** [comment]
on macOS we disabled libglvnd by default, but it can still be enabled.  There may still be some issues related to use of the deprecated(?) GLUT and GLU frameworks on macOS.  I'm not sure what to do about those -- on my machine I symlinked `GLUT` to `GLUT.tbd` and that got things building, but that's certainly not a general solve.

**Comment by davvid** [comment]
Regarding the `GLUT.tbd` stuff, it looks like it was reported to the cmake maintainers[1].  There's some other workarounds in the issue that can be used with older cmake versions.

https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5601
